package com.agutierg.hits2013.constants;

public class ConsultasSQL {

	// Tablas de la base de datos
	public static final String CREATE_TABLA_CANCIONES = "CREATE TABLE [Cancion] ([idCancion] INTEGER  NOT NULL PRIMARY KEY,[cantante] VARCHAR(255)  NOT NULL,[url] VARCHAR(255)  NOT NULL,[titulo] VARCHAR(255)  NOT NULL,[duracion] VARCHAR(255)  NOT NULL, [tipo] VARCHAR(25)  NOT NULL, [urlDescarga] VARCHAR(800) NOT NULL, [votos] INTEGER  NOT NULL, [insertDate] DATETIME NOT NULL)";

	// Insert para las canciones freaks
	public static final String INSERT_CANCION_PETER_ANGUILA = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('PETER ANGUILA','http://www.youtube.com/watch?v=u4jLZxmRy1s','El estilo de Peter La Anguila','1:59','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_COBRA_TAKA = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('JOAN','http://www.youtube.com/watch?v=ilMZ34XPnkg','La Cobra Taka Taka','2:41','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_CHIP_TORRES = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('CHIP TORRES','http://www.youtube.com/watch?v=WniL0xrH-JQ','Tú Me Pixeleas','2:45','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_PIO = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('PIO','http://www.youtube.com/watch?v=Qf49jWJiGb8','El Pollito Pío','2:39','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_PSY = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('PSY','http://www.youtube.com/watch?v=CH1XGdu-hzQ','Gangnam Style','5:02','3','http://a.tumblr.com/tumblr_max34rawkN1r0n4q8o1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_GALLO_KENTUCKY = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('JOAN','http://www.youtube.com/watch?v=8xrC3ROTCXI','El Gallo de Kentucky','2:55','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_SOY_CANI = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('SU_MORENITO_19','http://www.youtube.com/watch?v=h6k5qbt72Os','Soy Cani','3:28','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_RAFA_MORA = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('RAFA MORA Y SUBZE','http://www.youtube.com/watch?v=TPdsc45Sl8I','The Boss','4:55','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_CACHICHURRIS = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('DANIEL LUNA','http://www.youtube.com/watch?v=gshNvjvQCl8','El besito cachichurris','3:34','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_COMO_SE_MATA_GUSANO = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('LOS BORRACHOS','http://www.youtube.com/watch?v=4oftFbyfd5c','Como se mata el gusano','3:46','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_KO = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('K.O.','http://www.youtube.com/watch?v=w97SEjNThCk','Te Casaste La Cagaste','2:11','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_TOCAME_EL_WINDOWS = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('BRODY','http://www.youtube.com/watch?v=TK1WKqLKkUY','Tócame el Windows','3:06','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_LA_VACA = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('MALA FE','http://www.youtube.com/watch?v=1H9y_qDty-Y','La Vaca','4:13','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_UN_BYTE = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('CHIP TORRES','http://www.youtube.com/watch?v=pDVORKo8rYs','Te voy a dar un Byte','2:26','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_MAZORKA = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('ALFRID','http://www.youtube.com/watch?v=4OkmVtiPV0A','Chupa la mazorca','4:34','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_CRL_ALT = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('EL RENO RENALDO','http://www.youtube.com/watch?v=r_34hFLHdOY','Ctrl + Alt + Supr','4:24','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_SANTA_CLAUS = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('LORY MONEY','http://www.youtube.com/watch?v=di22vzZeTlk','Santa Claus','3:35','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_PAJEA = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('UPLOAD CINEMA','http://www.youtube.com/watch?v=5umJ9IQm_hM','Todo el mundo se pajea!','1:27','1','',0,current_timestamp)";
	public static final String INSERT_CANCION_OLA_KASE = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('LORY MONEY','http://www.youtube.com/watch?v=cvyUG4ul_aE','OLA K ASE','1:16','1','',0,current_timestamp)";

	// Insert para las canciones nuevas
	public static final String INSERT_CANCION_NEW_1 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Soraya','http://www.youtube.com/watch?v=9WeBC2ZFulE','Con fuego','3:14','2','http://media.bia2voice.in/Music/English/1391/12/Single/Soraya%20&%20Aqeel%20-%20Con%20Fuego%20(Radio%20Edit)/Soraya%20%26%20Aqeel%20-%20Con%20Fuego%20%28Radio%20Edit%29%20%5B128%5D.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_2 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Macaco','http://www.youtube.com/watch?v=VxnFirCYkdQ','Brindo por tí','4:49','2','http://a.tumblr.com/tumblr_mjlhj9oJQY1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_3 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Taylor Swift','http://www.youtube.com/watch?v=Tks6X4-sS6s','I knew you were trouble','3:32','2','http://www.allsong4u.com/songs/english/Taylor-Swift/04.%20I%20Knew%20You%20Were%20Trouble%20(www.allsong4u.com).mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_4 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Carly Rae Jepsen','http://www.youtube.com/watch?v=3xbcz7c2E6c','This kiss','3:56','2','http://tegos.ru/new/mp3_full/Carly_Rae_Jepsen_-_This_Kiss.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_5 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Auryn','http://www.youtube.com/watch?v=Bj1N-syNYjs','Heartbreaker','4:04','2','http://a.tumblr.com/tumblr_mjln318KMO1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_6 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('La Oreja de Van Gogh','http://www.youtube.com/watch?v=GIa0rCTIzVc','Otra vez me has sacado a bailar','3:37','2','http://a.tumblr.com/tumblr_mjlnwm9sVI1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_7 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('One Direction','http://www.youtube.com/watch?v=T4cdfRohhcg','Kiss you','3:11','2','http://sucodjmusic.tk/personal/tracks/One_Direction_Kiss_you.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_8 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('The Lumineers','http://www.youtube.com/watch?v=zvCBSSwgtg4','Ho hey','2:42','2','http://knrk.radiotown.com/FreeDownloads/TheLumineers_HoHey.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_9 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Rasel','http://www.youtube.com/watch?v=-jPQkTQgTMQ','Viven','3:35','2','http://a.tumblr.com/tumblr_mjlo7uNmev1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_10 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Calvin Harris','http://www.youtube.com/watch?v=dGghkjpNCQ8','Feel so close','4:07','2','http://aerialnoise.files.wordpress.com/2011/11/feel-so-close.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_11 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Pitbull','http://www.youtube.com/watch?v=1-fCTnIdHK8','Feel this moment','3:51','2','http://www.tegos.ru/new/mp3_full/Pitbull_feat_Christina_Aguilera_-_Feel_This_Moment.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_12 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Bon Jovi','http://www.youtube.com/watch?v=chXJFjrl-Q4','Because we can','4:02','2','http://alternate1.frendz4m.com/attachments/61/2/9/1357625310-frendz4m.com-Bon_Jovi_-_Because_We_Can_-_By_shaikh.shahid.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_13 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Flo Rida','http://www.youtube.com/watch?v=OLuWHr6-0YQ','I cry','3:53','2','http://mp3.wapos.ru/base/5/b/5/4036/wapos118669.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_14 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('David Guetta','http://www.youtube.com/watch?v=xyqQ4iT4IeU','Just one last time','4:16','2','http://tegos.ru/new/mp3_full/David_Guetta_feat_Taped_Rai_-_Just_One_Last_Time.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_15 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Olly Murs','http://www.youtube.com/watch?v=4aQDOUbErNg','Troublemaker','3:05','2','http://a.tumblr.com/tumblr_mcgj061uAN1r3v0vso1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_16 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Pink','http://www.youtube.com/watch?v=yTCDVfMz15M','Try','4:10','2','http://zaycev-mp3.net/mp3/pink_try_[zaycev-mp3.net].mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_17 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Of Monsters and Men','http://www.youtube.com/watch?v=ghb6eDopW8I','Little talks','4:15','2','http://themuseinmusic.com/wp-content/uploads/2011/05/1269-Little-Talks-1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_18 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Luís López, Baby Noel','http://www.youtube.com/watch?v=9PFNfpF1Fa4','I am doing fine','2:01','2','http://a.tumblr.com/tumblr_mjlonzsSgh1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_19 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Mastiksoul, David Anthony, Taylor Jones','http://www.youtube.com/watch?v=k2nmVUIXLho','Hurricane','3:37','2','http://a.tumblr.com/tumblr_mjlp4jyqgU1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_20 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Dani Moreno feat. Romy','http://www.youtube.com/watch?v=x_MIlYiJY6A','Low Break it','3:38','2','',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_21 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Justin Timberlake','http://www.youtube.com/watch?v=IsUsVbTj2AY','Suit & Tie','5:31','2','http://descargas.abrelaboca.com/Justin_Timberlake_ft_Jay-Z-Suit_and_Tie.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_NEW_22 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Nena Daconte','http://www.youtube.com/watch?v=JDtU4d1nB7A','Disparé','3:07','2','http://a.tumblr.com/tumblr_mjyjf2HF4J1s8smupo1.mp3',0,current_timestamp)";

	// Insert para las canciones
	public static final String INSERT_CANCION_1 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Melendi','http://www.youtube.com/watch?v=YbADVar8tjY','Lágrimas desordenadas','3:50','3','http://a.tumblr.com/tumblr_mjn7esCZRn1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_2 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Will.I.Am','http://www.youtube.com/watch?v=kYtGl1dX5qI','Scream & shout','4:52','3','http://a.tumblr.com/tumblr_mdmewuGdIQ1qzzktto1_r1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_3 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Bruno Mars','http://www.youtube.com/watch?v=e-fA-gBCkj0','Locked out of heaven','3:55','3','http://generations.fr/media/son/bruno-mars-locked-out-of-heaven.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_4 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Swedish House Mafia','http://www.youtube.com/watch?v=r1MN4pR5wXM','Dont you worry child','5:17','3','http://a.dolimg.com/en-US/radiodisney/media/audio/mp3/SwedishHouseMafia_DontYou.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_5 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Ke$ha','http://www.youtube.com/watch?v=BmV2zPXMzdI','Die young','3:41','3','http://www.fm-tv.ru/c/music/ke$ha_-_die_young_demo.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_6 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('The Script','http://www.youtube.com/watch?v=mk48xRzuNvA','Hall of fame','3:54','3','http://muzok.net/mp3/76/The_Script_Feat_Will.I.Am_-_Hall_Of_Fame.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_7 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Maroon 5','http://www.youtube.com/watch?v=BpypkvZjJiI','One more night','3:36','3','http://newmp3.name/mp3p/21/20611/128/128_maroon_5_one_more_night.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_8 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Pablo Alborán','http://www.youtube.com/watch?v=YlHhW7bpNlc','Tanto','4:16','3','http://a.tumblr.com/tumblr_mdjl24FiRn1qjvnc4o1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_9 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Estopa','http://www.youtube.com/watch?v=l6zhmJr4h2g','Empanados','3:32','3','http://www.programacionfm.com.ar/estrenos/%5B12-11-30%5DESTRENO.%20Estopa%20-%20Empanados.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_10 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Alejandro Sanz','http://www.youtube.com/watch?v=YNWllwNDunE','Mi marciana','4:42','3','http://www.genesis981.com.mx/mp3/mi_marciana.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_11 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Alicia Keys','http://www.youtube.com/watch?v=lWA2pjMjpBs','Girl on fire','4:43','3','http://www.woo55.pk/adata/6046/06.%20Girl%20On%20Fire%20(Inferno%20Version)%20(Feat%20Nicki%20Minaj)%20(www.SongsLover.pk).mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_12 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Rihanna','http://www.youtube.com/watch?v=9WeBC2ZFulE','Diamonds','3:14','3','http://dl-mahmusic20.in/1391/Dey/Album/Billboard%202012%20Year%20end%20Top%20Hot%20100%20Songs%20Charts%20%5b128%5d/94%20-%20Diamonds%20-%20Rihanna.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_13 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Maldita Nerea','http://www.youtube.com/watch?v=nwPZ9y1-PAQ','La respuesta no es la huida','4:49','3','http://www.programacionfm.com.ar/estrenos/[13-02-15]ESTRENO.%20Maldita%20Nerea%20-%20La%20Respuesta%20No%20Esta%20En%20La%20Huida.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_14 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Adele','http://www.youtube.com/watch?v=FlsBObg-1BQ','Set fire to the rain','4:00','3','http://safetyfunandlearning.files.wordpress.com/2011/08/adele-set-fire-to-the-rain.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_15 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Robbie Williams','http://www.youtube.com/watch?v=gtOV7bp-gys','Candy','3:23','3','http://tegos.ru/new/mp3_full/Robbie_Williams_-_Candy.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_16 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Pitbull','http://www.youtube.com/watch?v=i0vFid2tKbI','Dont stop the party','3:25','3','http://a.tumblr.com/tumblr_maxtde1xnF1rbmxclo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_17 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Katy Perry','http://www.youtube.com/watch?v=k0BWlvnBmIE','Wide awake','4:37','3','http://a.tumblr.com/tumblr_m14wrfDkUw1qevtumo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_18 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Avicii, Nicky Romero','http://www.youtube.com/watch?v=bek1y2uiQGA','I could be the one','4:46','3','http://ru-fm.ru/files/mp3/bfa4093b933c72f81dee64d71907db44.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_19 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Alesso, Matthew Koma','http://www.youtube.com/watch?v=EGYaxYaxD_M','Years','4:38','3','http://everythinglooksbrighter.files.wordpress.com/2012/08/alesso-ft-matthew-koma-years-vocal-extended-mix.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_20 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Wally López, Jamie Scott','http://www.youtube.com/watch?v=TUTezvLyKF0','You cant stop the beat','3:43','3','http://a.tumblr.com/tumblr_mjn8jk32UL1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_21 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Sebastian Ingrosso, Tommy Trash','http://www.youtube.com/watch?v=4a-bdOGBwEQ','Reload','4:04','3','http://everythinglooksbrighter.files.wordpress.com/2012/09/sebastian-ingrosso-tommy-trash-reload-original-mix.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_22 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Calvin Harris, Florence Welch','http://www.youtube.com/watch?v=17ozSeGw-fY','Sweet nothing','4:29','3','http://www.tegos.ru/new/mp3_full/Calvin_Harris_feat_Florence_Welch_-_Sweet_Nothing.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_23 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('David Guetta Feat. Sia','http://www.youtube.com/watch?v=PVzljDmoPVs','She Wolf','3:58','3','http://a.tumblr.com/tumblr_mb70r23nQM1qautj0o1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_24 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Nicki Minaj','http://www.youtube.com/watch?v=vdrqA93sW-8','Pound the alarm','4:14','3','http://a.tumblr.com/tumblr_m2gqrqyXzq1qzmu1xo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_25 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Dikko','http://www.youtube.com/watch?v=2ciNnlbGNUI','In the night','3:11','3','http://a.tumblr.com/tumblr_mjn8u2mCZm1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_26 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Pablo Alborán','http://www.youtube.com/watch?v=8P6Afvo37ns','El beso','4:24','3','http://a.tumblr.com/tumblr_mftiztnTwv1r029l1o1_r1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_27 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('James Arthur','http://www.youtube.com/watch?v=lJqbaGloVxg','Impossible','3:33','3','http://a.tumblr.com/tumblr_mjyd2qRcwQ1rv21xlo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_28 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Imagine Dragons','http://www.youtube.com/watch?v=sENM2wA_FTg','Its time','4:07','3','http://a.tumblr.com/tumblr_mg9ok9gSYm1ry6cufo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_29 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Snow Patrol','http://www.youtube.com/watch?v=AOBs8dU4Pb8','Run','4:27','3','http://a.tumblr.com/tumblr_ly146dZm6O1r1av0ko1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_30 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Linkin Park','http://www.youtube.com/watch?v=ScNNfyq3d_w','Castle of Glass','4:50','3','http://a.tumblr.com/tumblr_mjkasmUssh1s7gatho1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_31 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Rihanna ft. Mikky Ekko','http://www.youtube.com/watch?v=JF8BRvqGCNs#_=_','Stay','4:08','3','http://a.tumblr.com/tumblr_men3loyOef1r2um55o1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_32 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Adele','http://www.youtube.com/watch?v=StJLvbPIvTw','Skyfall','4:48','3','http://a.tumblr.com/tumblr_mizgfsk4UX1s74x39o1.mp3',0,current_timestamp)";

	// Insert para las canciones latinas
	public static final String INSERT_CANCION_LAT_1 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Don Omar','http://www.youtube.com/watch?v=pu5PZugNiJU','Zumba','4:25','4','http://server88.musickapoz.com/files/3/gpupuu38nhtfmv/Don%20Omar%20-%20Zumba%20(Original)%20(www.LoMasRankiaO.com).mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_2 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Luan Santana','http://www.youtube.com/watch?v=HtpPvt1wyzU','Sogrão Caprichou','2:56','4','http://www.grandefm.com.br/base/www/grandefm.com.br/media/attachments/41/41/50ed6df193125e3e912f775fef6a8df25c839ad1a463f_01-luan-santana-2012-sograo-caprichou.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_3 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Tan Bionica','http://www.youtube.com/watch?v=ZCPACcVgJ3U','Ciudad mágica','3:30','4','http://www.fmbrava.net.ar/images/songs/tan_bionica_ciudad_magica.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_4 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Daddy Yankee','http://www.youtube.com/watch?v=6BTjG-dhf5s','Limbo','4:15','4','http://a.tumblr.com/tumblr_makhurqpnY1rylu14o1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_5 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Jesse & Joy ft. Mario Doom','http://www.youtube.com/watch?v=OK_KvknlJxA','Llorar','5:01','4','http://variado.co/music/various/Jesse%20y%20Joy%20Ft.%20Mario%20Domm%20-%20Llorar%20(www.variado.net).mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_6 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Carlos Vives','http://www.youtube.com/watch?v=CJ_zRSv3Hr8','Volví a nacer','5:04','4','http://intervallenato.com/inicio/wp-content/uploads/2012/09/Volvi-A-Nacer-_Carlos-Vives.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_7 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Airbag','http://www.youtube.com/watch?v=FIR-hrPXxzA','Cae el sol','4:56','4','http://sucodjmusic.tk/personal/nuevos/Airbag_Cae_el_sol.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_8 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Romeo Santos','http://www.youtube.com/watch?v=MpHcxM0lpFI','Malevo','3:40','4','http://fdcmusic.net/files/Romeo%20Santos%20-%20Malevo%20(Www.FDCmusic.Net).mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_9 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Thalia','http://www.youtube.com/watch?v=tdMxSLlFFio','Manías','3:53','4','http://media.elsiglodetorreon.com.mx/files/mp3/thaliamanias.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_10 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Tito Bambino Ft Marc Anthony','http://www.youtube.com/watch?v=j9EoCHdnok4','¿Por qué les mientes?','3:49','4','http://f09.wapkafiles.com/download/b/1/1/63049_b11a3f70a95fab5872735e6a.mp3/3caa9ac8ea6d71b196a5/Tito%20El%20Bambino%20ft.%20Marc%20Anthony%20-%20Por%20Que%20Les%20Mientes.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_11 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Carlos Vives ft. Michel Telo','http://www.youtube.com/user/MichelTelo11?v=wXV-9G5cQiU','Como le gusta a tu cuerpo','3:51','4','http://www.bpmsupreme.com/store/mp3preview/Audio%20Previews%202013/Carlos%20Vives%20ft%20Michel%20Telo%20-%20Como%20Le%20Gusta%20a%20Tu%20Cuerpo%20(Intro%20Clean).mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_12 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Wisin & Yandel ft. Chris Borwn y T Pain','http://www.youtube.com/watch?v=lr41vq3-1Bs','Algo me gusta de ti','4:31','4','http://derkommissar.com.ar/dir/003%20-%20AUDIO%20KILLERS%20REMIX%20VOL.%201/audio%20killers%20remix%201/16%20-%20SKORPION%20DJ/01%20-%20Wisin%20%26%20Yandel%20Ft.%20Chris%20Brown%20%26%20T-Pain%20-%20Algo%20Me%20Gusta%20De%20Ti%20%28Skorpion%20Dj%29.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_13 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Zezé di Camargo & Luciano ft. Paula Fernandes','http://www.youtube.com/watch?v=dcqQxaU-YQY','Criação Divina','3:25','4','http://a.tumblr.com/tumblr_mjn90qts0K1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_14 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Elvis Crespo ft Fito Blanko','http://www.youtube.com/watch?v=O1B_MQU14Lg','Pegaito suavecito','5:19','4','http://www.reggaetonurbano.be/wp-content/uploads/2012/07/Elvis-Crespo-ft-Fito-Blanko-Pegadito-Suavecito-Remix.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_15 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Michel Teló','http://www.youtube.com/watch?v=jt6-zWaGUZQ','Uma Canção de Amor','2:58','4','',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_16 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Rio Roma','http://www.youtube.com/watch?v=cyxBoEybfew','Tan solo un minuto','3:09','4','http://a.tumblr.com/tumblr_lw8jjrudkQ1r3jrxto1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_17 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Enrique Iglesias ft. Sammy Adams','http://www.youtube.com/watch?v=f_EiqPp-vBM','Finally Found You','3:58','4','http://a.tumblr.com/tumblr_mcm6m7XfTy1qdpi6io1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_18 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Chino y Nacho ft. Potro Alvarez','http://www.youtube.com/watch?v=Fzkx1YO0Koc','Regálame un muack','5:33','4','http://www.radioelsol.com/top20/4.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_19 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Poncho','http://www.youtube.com/watch?v=UaLj8PhrZ3k','Take my hand','4:48','4','http://www.fmbrava.net.ar/images/songs/poncho-take-my-hand.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_20 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Guaco','http://www.youtube.com/watch?v=BSQoW0hcA0M','Vivo','3:27','4','http://www.albaciudad.org/musica/nacionales/90008%20-%20Guaco%20-%20Vivo.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_21 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Daddy Yankee','http://www.youtube.com/watch?v=UnTn0ZkTczo','Pasarela','3:39','4','http://freshmp3music.ru/music/05.2012/daddy_yankee_-_pasarela_(www.freshmp3music.ru).mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_22 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('DCS ft. Juan Magan','http://www.youtube.com/watch?v=YB52nMJx4gA','Ángelito sin alas','3:25','4','http://a.tumblr.com/tumblr_mjn9cgovZL1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_23 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('J Alvarez','http://www.youtube.com/watch?v=9bM_Cptnb8M','Hablame De Ti','3:17','4','http://sectorurbano.net/dmdocuments/reggaeton/febrero/J%20Alvarez%20-%20Hablame%20De%20Ti.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_24 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Lui G 21 Plus','http://www.youtube.com/watch?v=9JJLUzDoFUU','Un Beso','3:30','4','http://www.djyellow.com/wp-content/uploads/2013/02/Lui-G_21_Plus_-_Un_Beso.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_25 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Killatonez Ft. Ñengo Flow','http://www.youtube.com/watch?v=jjWRYgUnX3Y','Relación Pasajera','5:05','4','http://a.tumblr.com/tumblr_mjna31F93d1s8smupo1.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_26 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Yandar & Yostin Feat. Andy Rivera','http://www.youtube.com/watch?v=Rfc6rh0Sm0I','Te Pintaron Pajaritos','3:04','4','http://main.mdigital.org/back/salsa/server/2012/yandar%20y%20yostin-te%20pintaron%20pajaritos.mp3',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_27 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Reik','http://www.youtube.com/watch?v=Q2ejkHig2u0','Con la Cara en Alto','3:50','4','',0,current_timestamp)";
	public static final String INSERT_CANCION_LAT_28 = "INSERT INTO Cancion (cantante,url,titulo,duracion,tipo,urlDescarga,votos,insertDate) VALUES ('Aleks Syntek Dueto con Malú','http://www.youtube.com/watch?v=qHfkP4rjX8w','Solo el Amor nos Salvará','3:49','4','http://a.tumblr.com/tumblr_mjyjghbqUM1s8smupo1.mp3',0,current_timestamp)";

}
